//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rad1G.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadPodaci
    {
        public int Id { get; set; }
        public int ObveznikId { get; set; }
        public string ZaposlenikId { get; set; }
        public Nullable<int> BrutoPlacaMuskarci { get; set; }
        public Nullable<int> NetoPlacaMuskarci { get; set; }
        public Nullable<int> BrojZaposlenihMuskarci { get; set; }
        public Nullable<int> BrutoPlacaZene { get; set; }
        public Nullable<int> NetoPlacaZene { get; set; }
        public Nullable<int> BrojZaposlenihZene { get; set; }
        public Nullable<int> BrutoPlacaVisokaStrucnaSprema { get; set; }
        public Nullable<int> NetoPlacaVisokaStrucnaSprema { get; set; }
        public Nullable<int> BrojZaposlenihVisokaStrucnaSprema { get; set; }
        public Nullable<int> BrutoPlacaVisaStrucnaSprema { get; set; }
        public Nullable<int> NetoPlacaVisaStrucnaSprema { get; set; }
        public Nullable<int> BrojZaposlenihVisaStrucnaSprema { get; set; }
        public Nullable<int> BrutoPlacaSrednjaStrucnaSprema { get; set; }
        public Nullable<int> NetoPlacaSrednjaStrucnaSprema { get; set; }
        public Nullable<int> BrojZaposlenihSrednjaStrucnaSprema { get; set; }
        public Nullable<int> BrutoPlacaNizaStrucnaSprema { get; set; }
        public Nullable<int> NetoPlacaNizaStrucnaSprema { get; set; }
        public Nullable<int> BrojZaposlenihNizaStrucnaSprema { get; set; }
        public Nullable<int> BrutoPlacaVisokokvalificirani { get; set; }
        public Nullable<int> NetoPlacaVisokokvalificirani { get; set; }
        public Nullable<int> BrojZaposlenihVisokokvalificirani { get; set; }
        public Nullable<int> BrutoPlacaKvalificirani { get; set; }
        public Nullable<int> NetoPlacaKvalificirani { get; set; }
        public Nullable<int> BrojZaposlenihKvalificirani { get; set; }
        public Nullable<int> BrutoPlacaPriuceni { get; set; }
        public Nullable<int> NetoPlacaPriuceni { get; set; }
        public Nullable<int> BrojZaposlenihPriuceni { get; set; }
        public Nullable<int> BrutoPlacaNekvalificirani { get; set; }
        public Nullable<int> NetoPlacaNekvalificirani { get; set; }
        public Nullable<int> BrojZaposlenihNekvalificirani { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Obveznik Obveznik { get; set; }
    }
}
